export const allTags = [
  "3D Models",
  "Accounting",
  "Accredited Course",
  "Adaptive Learning",
  "Adult Learners",
  "Algebra",
  "Anatomy",
  "Artificial Intelligence",
  "Asynchronous Learning",
  "Auditory Learners",
  "Audio Description",
  "Audio Lessons",
  "Auto-Grading",
  "Automotive",
  "Beginner",
  "Biology",
  "Braille Compatibility",
  "Business & Economics",
  "Calculus",
  "Case Studies",
  "Case Study",
  "Certificate of Completion",
  "Certification Preparation",
  "Challenging",
  "Chat Rooms",
  "Chemistry",
  "Chinese",
  "C++",
  "Closed Captioning",
  "Collaboration",
  "College/University",
  "Complex",
  "Computer Science",
  "Construction",
  "Continuing Education Credits",
  "Creativity",
  "Critical Thinking",
  "Custom Learning Path",
  "Data Science",
  "Discussion-Based",
  "Discussion Forums",
  "Downloadable Worksheets",
  "Earth Science",
  "Easy",
  "Economics",
  "Education",
  "E-Books",
  "Elementary School",
  "English",
  "Entertainment",
  "Entrepreneurship",
  "Environmental Science",
  "Essay",
  "Exam Certification",
  "Expert",
  "Fast-Track",
  "Film & Media",
  "Finance",
  "Flexible Deadlines",
  "Flashcards",
  "French",
  "Full Course",
  "Future Trends",
  "Gamified Learning",
  "Games",
  "Geography",
  "German",
  "GMAT",
  "Graphic Design",
  "Graded Assignments",
  "Group Learning",
  "Group Projects",
  "Hands-on Projects",
  "Hands-On Practice",
  "Healthcare",
  "High Contrast",
  "High School",
  "Historical Context",
  "History",
  "Hindi",
  "Humanities",
  "Hybrid Learning",
  "Information Technology",
  "Infographics",
  "Instructor-Led Feedback",
  "Instructor-Led Learning",
  "Interactive Quizzes",
  "Interactive Whiteboard",
  "Intermediate",
  "Intensive",
  "Java",
  "Javascript",
  "Kinesthetic Learners",
  "Knowledge Building",
  "Law",
  "Linguistics",
  "Literature Analysis",
  "Live Classes",
  "LMS Integration",
  "Log",
  "Machine Learning",
  "Manufacturing",
  "Marketing",
  "Mastery Level",
  "Mathematics",
  "Medium",
  "Middle School",
  "Mobile-Friendly",
  "MOOC",
  "Multilingual",
  "Music Theory",
  "Multiple Choice",
  "Nutrition",
  "Offline Access",
  "One-on-One Coaching",
  "Online Learning",
  "Peer Assessments",
  "Peer Collaboration",
  "Peer Review",
  "Performing Arts",
  "Personalized Feedback",
  "Philosophy",
  "Physics",
  "Political Science",
  "Podcasts",
  "Practice Problems",
  "Presentation Slides",
  "Problem Solving",
  "Professional Development Units",
  "Programming",
  "Projects",
  "Psychology",
  "Public Health",
  "Python",
  "React",
  "Real-Time Feedback",
  "Real-World Application",
  "Real-World Scenarios",
  "Recorded Webinars",
  "Recommendations Based on Progress",
  "Reading/Writing Learners",
  "Retail",
  "Robotics",
  "SAT",
  "Scenario-Based Learning",
  "Scheduled",
  "Screen Reader Compatible",
  "Self-Assessment",
  "Self-Paced",
  "Self-Paced Learning",
  "Short",
  "Short Answer",
  "Simulation",
  "Skill Development",
  "Sociology",
  "Source Code",
  "Spanish",
  "Statistics",
  "Study Guides",
  "Subtitles",
  "Synchronous Learning",
  "Telecommunications",
  "Test Preparation",
  "Text-to-Speech",
  "Theory-Based",
  "Trigonometry",
  "Tutorials",
  "Upper-Level Analysis",
  "Upper-Level Physics",
];
